Add the cluster's `minPinners` value to the health check response.
SkynetLabs/pinner pull request #23
Opened 2022-05-17 14:20 UTC by ro-tex

# PULL REQUEST

## Overview

## Example for Visual Changes

## Checklist
Review and complete the checklist to ensure that the PR is complete before assigned to an approver.
 - [ ] All new methods or updated methods have clear docstrings
 - [ ] Testing added or updated for new methods
 - [ ] Verify if any changes impact the WebPortal Health Checks
 - [ ] Approriate documentation updated
 - [ ] Changelog file created

## Issues Closed
Closes SKY-428

2022-05-17 15:31 UTC, MSevey requested changes

2022-05-19 14:27 UTC, ro-tex commented on conf/configuration.go
> +		return defaultMinPinners, err
That's a good point. I wasn't sure about this decision, either. It kinda worked a little bit better with the health endpoint in the case where the DB is dead but I guess that's fine. I'll go back to 0.

2022-05-19 14:30 UTC, ChrisSchinnerl approved these changes

2022-05-19 14:39 UTC, MSevey approved these changes

2022-05-19 14:39 UTC, merged